### ISSUE TITLE
Constant time crate

### ISSUE THREAD

**Issue by burdges** [isislovecruft/curve25519-dalek#1]
There is a nice crate [consistenttime](https://github.com/valarauca/consistenttime) with various constant time integer operations, btw.

**Comment by hdevalence** [comment]
Unfortunately, we're not comfortable with having core operations for this crypto in a crate we don't control and have no guarantees over, so we will not be using that crate.  We already have some ideas about how we would like to use `rustc` to check for timing and cache leaks, but when we implement them, we'll do so in our own crate.
