### ISSUE TITLE
Decaf support

### ISSUE THREAD

**Issue by hdevalence** [isislovecruft/curve25519-dalek#10]
We would like to implement Decaf, to get a prime-order group without concerns about cofactors.  Mike Hamburg kindly pointed us to his code here: https://sourceforge.net/p/ed448goldilocks/code/ci/curve25519-work/tree/

**Comment by hdevalence** [comment]
Some work on this is in #26.

**Comment by isislovecruft** [comment]
We have experimental Decaf support, if compiled with `--features=yolocrypto`. We still need testvectors from Mike's code.

**Comment by isislovecruft** [comment]
This is succeeded by #76.
