### ISSUE TITLE
Validate points

### ISSUE THREAD

**Issue by burdges** [isislovecruft/curve25519-dalek#49]
It's maybe worth providing, or recommending, some side function to validate points.  I donno if this should just rule out obviously bad points, or maybe say `(6..246).contains( compressed_point.iter().map(|x| x.count_ones()).sum() )`, or even a more [interesting](http://www.ciphersbyritter.com/RES/RANDTEST.HTM#Feldman87) [randomness test](https://en.wikipedia.org/wiki/Randomness_tests#Specific_tests_for_randomness) based on FFTs.

**Comment by hdevalence** [comment]
Point validation is done at decompression time -- either an input will decompress successfully to a valid curve point, or else return `None`. 

I think that any notion of "good" or "bad" points beyond whether the point is valid or not is protocol-specific and therefore out of scope for this library.
