### ISSUE TITLE
Improve Scalar API

### ISSUE THREAD

**Issue by hdevalence** [isislovecruft/curve25519-dalek#5]
The `Scalar` API should be reworked to make it better for general-purpose use.  This issue is for tracking those changes (and figuring out what they should be). For instance, it doesn't currently implement Add or Mul traits, and just has a single `multiply_add` function.

In my feature branch https://github.com/hdevalence/curve25519-dalek/tree/feature/split-scalar-type  I split code off of the `Scalar` type into an `UnpackedScalar` type.  There's some issue here about whether to represent a `Scalar` as bytes (allowing easy access to the bits for scalar multiplication) or as limbs (for arithmetic).  I don't know which is the better thing to optimize for in a general-purpose library.

For now, maybe we should have `Scalar` implement arithmetic by unpacking, calling an impl in `UnpackedScalar`, and then repacking?  That way, users who just want to implement something can use `Scalar`s and have it work, but people can use `UnpackedScalar` to avoid overhead if they want to. (This shouldn't be a bottleneck, so it's not really that important -- whatever is simplest and cleanest is best).

Comments?

**Comment by isislovecruft** [comment]
Did we finish all of this yet?

**Comment by isislovecruft** [comment]
We've made a bunch of API improvements between 0.6.0 and 0.8.0, including making both `s * P` and `P * s` work for both `ExtendedPoint`s and `DecafPoint`s.  I'm calling this done.  If we have more specific improvements to the Scalar API, we should open a less-vague ticket. :)
