### ISSUE TITLE
Accelerate scalar inversion

### ISSUE THREAD

**Issue by hdevalence** [isislovecruft/curve25519-dalek#68]
The Back-Maxwell rangeproof construction we use in `dalek-rangeproofs` requires scalar inversion. Right now we just have an easy and naive implementation with no optimization, but which is nearly as expensive as a full point*scalar operation.

It could be made faster by some combination of:

- [x] using fixed-window exponentiation with a lookup table (see the constant-time scalar-point multiplication for an example)
- [x] adding an implementation of squaring for scalars
- [x] optimizing the scalar arithmetic: maybe Karatsuba, Montgomery reduction, or some combination?
- [x] maybe 64-bit implementation of scalar arithmetic ?

**Comment by hdevalence** [comment]
#71 adds an implementation of squaring for scalars.

**Comment by isislovecruft** [comment]
#72 uses a custom (more efficient) addition chain, this replaces the goal of using a fixed-window exponentiation.

**Comment by isislovecruft** [comment]
#75 implements the Karatsuba portion of goal number 3.

**Comment by hdevalence** [comment]
Closing this issue now that Floodyberry's 64-bit scalar code is merged.
