### ISSUE TITLE
Some "as" cast replacements

### ISSUE THREAD

**Issue by leonardo-m** [isislovecruft/curve25519-dalek#73]
I suggest to replace the code pattern "`as u128`"  with "`u128::from()`".

So in the `field_64bit.rs` file code like:

`fn m(x: u64, y: u64) -> u128 { (x as u128) * (y as u128) }`

Becomes:

`fn m(x: u64, y: u64) -> u128 { u128::from(x) * u128::from(y) }`

The point of this apparently pointless change is that "as" casts are bug-prone,  while from() is reliable. In general I suggest to minimize the number of "as" in a Rust program.

**Comment by isislovecruft** [comment]
Hi @leonardo-m!

My understanding is that the idea that

> "as" casts are bug-prone

is due to the fact that bugs result from developers not expecting truncating behaviour when casting downwards, e.g. `u128::MAX as u64`.

**Comment by leonardo-m** [comment]
You're welcome, happy to help your project :-)

"as" casts are bug-prone for various reasons, one reason is that they specify the destination type only, so if the start type changes because of code refactorings, the cast keeps happily working, sometimes losing information. So wise programmers should minimize the number of "as" casts in their code. from() was invented to tell apart lossless casts from lossy ones.

**Comment by hdevalence** [comment]
In the case we're discussing (low-level arithmetic), the starting types are pretty much fixed.  In the specific example given, they're fixed in the function signature, which is type-checked, so using `from()` adds no additional type safety.
